const WATCHED = "WATCHED";
const FETCH_VIDEOS_REQUEST = "FETCH_VIDEOS_REQUEST";
const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS";
const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE";
const VIDEO_CLICKED = "VIDEO_CLICKED";
const VIDEO_CLOSED = "VIDEO_CLOSED";
const ADD_TO_WATCHLATER = "ADD_TO_WATCHLATER"

const LOADING = "LOADING";

export {
  WATCHED,
  FETCH_VIDEOS_REQUEST,
  FETCH_VIDEOS_SUCCESS,
  FETCH_VIDEOS_FAILURE,
  VIDEO_CLICKED,
  VIDEO_CLOSED,
  ADD_TO_WATCHLATER
};
