const HANDLE_CHANGE = 'HANDLE_CHANGE';
const GET_VIDEOS = 'GET_VIDEOS';
const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
const TOGGLE_SEARCH = 'TOGGLE_SEARCH';

export { HANDLE_CHANGE, GET_VIDEOS, GET_SEARCH_RESULTS, TOGGLE_SEARCH };