const FETCH_CATEGORY_VIDEOS_REQUEST = "FETCH_CATEGORY_VIDEOS_REQUEST";
const FETCH_CATEGORY_VIDEOS_SUCCESS = "FETCH_CATEGORY_VIDEOS_SUCCESS";
const FETCH_CATEGORY_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE";
const FETCH_VIDEOS_CATEGORIES = "FETCH_VIDEOS_CATEGORIES";
const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";

export {
  FETCH_CATEGORY_VIDEOS_REQUEST,
  FETCH_CATEGORY_VIDEOS_SUCCESS,
  FETCH_CATEGORY_VIDEOS_FAILURE,
  FETCH_VIDEOS_CATEGORIES,
  SET_ACTIVE_CATEGORY
};
