const GET_CREATORS_REQUEST = "GET_CREATORS_REQUEST";
const GET_CREATORS_SUCCESS = "GET_CREATORS_SUCCESS";
const GET_CREATORS_FAILURE = "GET_CREATORS_FAILURE";
const FOLLOW_CREATOR = "FOLLOW_CREATOR"

export { FOLLOW_CREATOR, GET_CREATORS_REQUEST, GET_CREATORS_SUCCESS, GET_CREATORS_FAILURE };
